### ISSUE TITLE
Source to Destruction Simluator (u would either leave this here or make it open sourced ur self if this script hub really is open sourced)

### ISSUE THREAD

**Issue by yofriendfromschool1** [borthdayzz/starhook#2]
https://raw.githubusercontent.com/yofriendfromschool1/leaked-src-scripts-lol/main/destructionsimulatorinfmoneyBirthX.lua

**Comment by borthdayzz** [comment]
why u so obsessed with me 💀🙏
u wanna date me or what

**Comment by borthdayzz** [comment]
nah im too lazy
